### ISSUE TITLE
请问下这个博客可以增加一个目录吗

### ISSUE THREAD

**Issue by Archsx** [laysent/website#12]
您好，我很喜欢您的博客，但是在阅读“Things I Learned”这个部分的时候，由于没有目录，只能上一页 下一页的查找自己想要阅读的部分，感觉很吃力。希望能有一个目录的功能方便查找以及阅读。

**Comment by laysent** [comment]
😂我找时间开发一下

**Comment by Archsx** [comment]
会一直关注文章的更新的！

**Comment by laysent** [comment]
https://laysent.com/til/table-of-contents 我写了一个简陋的，先凑活着用吧😂
